### ISSUE TITLE
I cannot import mpl_token_metadata::instruction.

### ISSUE THREAD

**Issue by lucaslee129** [metaplex-foundation/mpl-token-metadata#102]
Hi, How are you, everyone. I hope this message finds you well.

I am a fresher to Solana, so now I am following the tutorial using anchor framework. But I faced the some problems while following that course.

Here is my dependencies.
```
[dependencies]
anchor-lang = {version = "0.29.0", features = ["init-if-needed"]}
anchor-spl = {version = "0.29.0", features = ["metadata"]}
mpl-token-metadata = "4.1.2"
```

I cannot import the instruction of mpl_token_metadata. 
Here is some of my code snipet.
```
...
use mpl_token_metadata::instruction::create_metadata_accounts_v3;
...
```

In this case, this error is occured.
```
use mpl_token_metadata::instruction::create_metadata_accounts_v3;
  |                         ^^^^^^^^^^^ could not find `instruction` in `mpl_token_metadata`
```

I am working for this error for about 4 hours, cannot find the solution.

Please help me, Thanks.

**Comment by ad7090** [comment]
same issue @lucaslee129 @katopz @thlorenz @enriquefynn @febo

**Comment by blockiosaurus** [comment]
Token Metadata is not an Anchor program and therefore doesn't export the Instructions in the same way. For details on how to CPI into the program, please see the Metaplex docs https://developers.metaplex.com/token-metadata/mint and select Rust (CPI) in the dialect switcher for code examples.
