### ISSUE TITLE
How to set the Metadata information of FT token?

### ISSUE THREAD

**Issue by NetGodFather** [metaplex-foundation/mpl-token-metadata#105]
All the places are about NFTs, no where is full sample code with information on how to set up FT tokens.

I read a lot of documents, but nothing is clear.

Can the administrator provide one?

**Comment by MarkSackerberg** [comment]
You can find a full guide on how to mint a fungible Token in our developer hub: https://developers.metaplex.com/guides/javascript/how-to-create-an-spl-token-on-solana
