### ISSUE TITLE
createCreateMetadataAccountV3Instruction is missing

### ISSUE THREAD

**Issue by y0unghe** [metaplex-foundation/mpl-token-metadata#123]
I am trying to use the function `createCreateMetadataAccountV3Instruction` to create an instruction. But I am getting the below error when importing to my Next.js project. The version I am using is the latest. But when I searched for the function in the current Github repo, this function did exist.

```
"@metaplex-foundation/mpl-token-metadata": "^3.2.1",
```

```
'"@metaplex-foundation/mpl-token-metadata"' has no exported member named 'createCreateMetadataAccountV3Instruction'. Did you mean 'CreateMetadataAccountV3InstructionData'?
```

**Comment by rosselpha** [comment]
yea. me too

**Comment by y4my4my4m** [comment]
Same

**Comment by MarkSackerberg** [comment]
Hey @y0unghe @rosselpha @y4my4my4m where did you find this?
`createCreateMetadataAccountV3Instruction` is a type, not a function. The function for it would be `createMetadataAccountV3`.

If you actually want to directly use that instruction you could use

```js
import {
  createMetadataAccountV3,
  mplTokenMetadata,
} from "@metaplex-foundation/mpl-token-metadata";
import { none } from "@metaplex-foundation/umi";

  const createMetadataAccountV3Ix = createMetadataAccountV3(umi, {
    mint: mint.publicKey,
    mintAuthority: umi.identity,
    isMutable: true,
    collectionDetails: none(),
    data: {
      name: "myToken",
      uri: "https://arweave.net/7BzVsHRrEH0ldNOCCM4_E00BiAYuJP_EQiqvcEYz3YY",
      symbol: "MT",
      sellerFeeBasisPoints: 0,
      creators: none(),
      collection: none(),
      uses: none(),
    },
  }).getInstructions()
```
This `createMetadataAccountV3` has an easier to use `createV1` wrapper though:
```js
import {  createV1,  mplTokenMetadata,  TokenStandard } from "@metaplex-foundation/mpl-token-metadata";

import {
  percentAmount,
} from "@metaplex-foundation/umi";
  const createV1Ix = createV1(umi, {
    mint: mint.publicKey,
    authority: umi.identity,
    name: "My NFT",
    uri: "https://arweave.net/7BzVsHRrEH0ldNOCCM4_E00BiAYuJP_EQiqvcEYz3YY",
    sellerFeeBasisPoints: percentAmount(5.5),
    tokenStandard: TokenStandard.Fungible,
  }).getInstructions()
``` 

or, depending on what kind of token you want to create there are [Create Helpers](https://developers.metaplex.com/token-metadata/mint#create-helpers) that requires even less input. For example `createFungible`:
```js
  await createFungible(umi, {
    mint,
    name: "myToken",
    uri: "https://arweave.net/7BzVsHRrEH0ldNOCCM4_E00BiAYuJP_EQiqvcEYz3YY",
    sellerFeeBasisPoints: percentAmount(0),
    decimals: tokenAmount.decimals,
  })
```

**Comment by xcaptain** [comment]
I find this from https://github.com/solana-developers/pirate-bootcamp/blob/main/quest-1/scripts/3.createTokenWithMetadata.ts#L121
And https://www.youtube.com/watch?v=0P8JeL3TURU&t=1529s

**Comment by xcaptain** [comment]
Also the official doc recommend using V2 version.
https://solana.com/developers/courses/tokens-and-nfts/token-program#make-some-token-metadata

Do you have any examples about how to use `createMetadataAccountV3` without using `umi` ?

**Comment by MarkSackerberg** [comment]
If you are using the same packages as the package.json of the pirate-bootcamp suggests (which is very outdated) it should be working fine.
The Solana.com docs you sent recommends to use package version 2 - which does not require Umi.

Personally i would absolutely recommend to follow our docs in the [developer hub](https://developers.metaplex.com/token-metadata/mint#creating-mint-and-metadata-accounts) on how to use umi and how to create Metadata.

**Comment by michaelessiet** [comment]
Isn't there a way to do this with just web3.js and the mpl-token-metadata package? Do we have to use umi?

**Comment by kuchaguangjie** [comment]
`"@metaplex-foundation/mpl-token-metadata": "^2.13.0",` this version solve the error

**Comment by joshdgeek** [comment]
i found this article very useful,
[](https://www.quicknode.com/guides/solana-development/spl-tokens/how-to-create-a-fungible-spl-token-with-the-new-metaplex-token-standard#run-your-code)

**Comment by joshdgeek** [comment]
i found this article to be very useful :

https://www.quicknode.com/guides/solana-development/spl-tokens/how-to-create-a-fungible-spl-token-with-the-new-metaplex-token-standard#run-your-code
