### ISSUE TITLE
How to Retrieve Token Metadata in 2024?

### ISSUE THREAD

**Issue by mahnunchik** [metaplex-foundation/mpl-token-metadata#126]
What is the simplest way to retrieve token metadata such as name, symbol, and decimals in 2024?

* The `@solana/spl-token-registry` is deprecated and lacks new tokens.
* The `@metaplex-foundation/mpl-token-metadata` has been updated from version 2 to version 3, resulting in complex dependencies to obtain minimal token information.

For example, tokens:
* `2b1kV6DkPAnxd5ixfnxCpjxmKwqjjaYmCZfHsFu24GXo` - PYUSD
* `Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB` - USDT

**Comment by MarkSackerberg** [comment]
Hey,
As I can see you got a answer onstaxkoverflow already. https://solana.stackexchange.com/a/15564
therefore I’ll close this issue. Let me know in case your issue still exists.

**Comment by fbettag** [comment]
I am using rust and it's absolutely unclear to me how i get metadata. I've been trying for 2 days straight.

A little more documentation (maybe just one example?) would be great.

Also https://developers.metaplex.com/token-metadata/fetch only shows it for TypeScript -.-
