### ISSUE TITLE
[Ported Issue] Docs are outdated

### ISSUE THREAD

**Issue by samuelvanderwaal** [metaplex-foundation/mpl-token-metadata#19]
https://github.com/metaplex-foundation/metaplex-program-library/issues/1122#issue-1762332570

**Comment by lastemp** [comment]
Hi Everyone, I would like to assist on this issue only that I need some guidance. I noted that the [docs](https://metaplex-foundation.github.io/metaplex-program-library/docs/token-metadata/) also contains outdated code reference as indicated on [code link](https://github.com/metaplex-foundation/metaplex-program-library/blob/caeab0f7/token-metadata/js/src/generated/instructions/CreateMetadataAccountV2.ts)

Is there a specific place I might need to go and update details so as to resolve the issue on the documentation?

**Comment by febo** [comment]
The code link refers to the new version of the NPM package – the docs for it are published [here](https://mpl-token-metadata-js-docs.vercel.app/). This is the same link found on the repo's README file.
