### ISSUE TITLE
Mint Account Remains Open Post-NFT Burn Even When Owned by Metaplex Program

### ISSUE THREAD

**Issue by dr497** [metaplex-foundation/mpl-token-metadata#57]
During the process of burning an NFT, all associated accounts (token account, metadata, edition, etc.) are correctly closed. However, the mint account remains open, even in instances where the mint account is owned by the Metaplex program.

**Comment by samuelvanderwaal** [comment]
Mint accounts on the original spl-token program cannot be closed--this is a restriction in the token program not the Metaplex one.

**Comment by dr497** [comment]
Thanks for the clarification, I did not realize this.
