### ISSUE TITLE
token2022

### ISSUE THREAD

**Issue by crypt0miester** [metaplex-foundation/mpl-token-metadata#59]
any eta on token2022 branch deployed on mainnet?

**Comment by febo** [comment]
The PR is going through an audit at the moment.

**Comment by travisbotello** [comment]
> The PR is going through an audit at the moment.

So I guess the current `AccountNotFoundError` error when trying to run `await fetchDigitalAsset(umi, tokenMint)` on a token2022 address is expected until then PR is merged? 

Or is there currently any other way of retrieving the metadata for token2022?

**Comment by febo** [comment]
> > The PR is going through an audit at the moment.
> 
> So I guess the current `AccountNotFoundError` error when trying to run `await fetchDigitalAsset(umi, tokenMint)` on a token2022 address is expected until then PR is merged?
> 
> Or is there currently any other way of retrieving the metadata for token2022?

Correct.

The PR has been merged to main and should be deployed by tomorrow.
