### ISSUE TITLE
Issue with Token Metadata

### ISSUE THREAD

**Issue by freegold** [metaplex-foundation/mpl-token-metadata#60]
In studying the architecture of what fields a meta dat file consists of I went to the descriptions for "token" and "nft" and "Sized Collection" and noticed 1 -  you don't have a side bar - that tells average joe or jill what the heck your acronyms stand for.   And 2 - when you talk about deprecation (axing) a mip-3 - and say that the main feature (receiving royalties) can be covered in another feature, I get confused. The mip-3 relates to a function within metadata of an nft. Yet in your dialog you go back and forth talking about "assets." Yet, this function has little to do with "assets" and everything to do with the metadata of an "nft." And yes an nft is in a class called "assets." But so is a car and a refrigerator and intellectual property. So, please be clear about what terms you are using. If you want to store metadata from a class of "assets" that include "nft" etc then you need to change the parameters for your metadata.  Also, when you say you will except "public input" then think of the lowest common denominator in this "class" called "public". How easy is it for the average Joe to leave comments here? You need an open (sign into to post) forum for public comments about your proposals, not a git directory!
thanks, Rick

**Comment by febo** [comment]
Not quite follow your comment: is this in reference to the Token Metadata docs in [https://developers.metaplex.com/token-metadata](https://developers.metaplex.com/token-metadata)?

**Comment by freegold** [comment]
Yes, Token Metadata docs, don't know of any other.  These were comments directed to the devs working on managing NFTs and  what you call fungible assets. Are you asking for the average persons to comment from reading your comments?  This obviously, isn't meant for the average persons comments because it's been 2 weeks for you to reply just to me. Why don't you offer a forum for comments? Like a Solana forum, open to the community? You really can't mix your NFTs and fungible assets in the same token metadata. Even your explanations in the Metadocs are confused. Maybe stick with assets (and then include subcategories ie car, house, bank account - i.e. fungible, nonfungible, neither) thanks again, Rick

**Comment by febo** [comment]
Metaplex Discord (https://t.co/kmuwlPVz0S) is the best place to address these queries. There are also forums discussing different topics related to NFTs on StackExchange (https://solana.stackexchange.com).
