### ISSUE TITLE
`mpl-token-metadata` starting with v2.0.0 does not contain Solana program code anymore

### ISSUE THREAD

**Issue by andreisilviudragnea** [metaplex-foundation/mpl-token-metadata#80]
Since v2.0.0, `mpl-token-metadata` is an SDK crate. The crate versions before that included the program code itself too.

Is there any other crate which now contains the removed `mpl-token-metadata` program code? Our project depends on some helper methods from the `mpl-token-metadata` program itself and we cannot update our codebase to Solana v1.17 because of this problem, since `mpl-token-metadata` v1.13.2 does not suport Solana v1.17.

**Comment by andreisilviudragnea** [comment]
@danenbm Any idea about supporting this in the future again?

**Comment by samuelvanderwaal** [comment]
Out of curiosity, what are the helper methods?

**Comment by danenbm** [comment]
Yes, please let us know the helper methods you are missing.  We have migrated a few projects from using the program crate to the Rust client crate, and can help with this process.

**Comment by andreisilviudragnea** [comment]
Hello, @danenbm. We are using some items from `token_metadata` Solana program for emulating some `token_metadata` instructions on our side: https://github.com/neonlabsorg/neon-evm/blob/develop/evm_loader/program/src/external_programs/metaplex.rs

**Comment by null-prophet** [comment]
same here, the PDA utils would be super helpful

**Comment by blockiosaurus** [comment]
@null-prophet all of the PDA helpers should be present in the new clients.

**Comment by null-prophet** [comment]
> @null-prophet all of the PDA helpers should be present in the new clients.

can you show me where as I searched the code for specific references and looked at the rust docs.

`find_master_edition_account` I couldn't find anywhere in the crate code.

![image](https://github.com/metaplex-foundation/mpl-token-metadata/assets/83577435/58a14401-9506-4db8-a338-6113aa6c48a1)

https://docs.rs/mpl-token-metadata/latest/mpl_token_metadata/all.html?search=find_master_edition_account

Am I looking in the wrong place?

**Comment by blockiosaurus** [comment]
PDA finders now live on their respective accounts.
https://docs.rs/mpl-token-metadata/latest/mpl_token_metadata/accounts/struct.MasterEdition.html#method.find_pda

**Comment by null-prophet** [comment]
Thanks @blockiosaurus 

How would I then access these if I was using these accounts or the original PDA methods in the checks for an account struct in Anchor? Sorry, I'm just new to this ecosystem and finding it hard to find any up to date information on the best way to do things. I'm following along with some NFT minting tutorials to get me up to speed but they are relying on much older `v1.x` instances of this crate.



```
    /// CHECK - address
    #[account(
        mut,
        address=find_metadata_account(&mint.key()).0,
    )]
    pub metadata_account: AccountInfo<'info>, // new
    /// CHECK: address
    #[account(
        mut,
        address=find_master_edition_account(&mint.key()).0,
    )]
    pub master_edition_account: AccountInfo<'info>, 
```

**Comment by samuelvanderwaal** [comment]
> Thanks @blockiosaurus
> 
> How would I then access these if I was using these accounts or the original PDA methods in the checks for an account struct in Anchor? Sorry, I'm just new to this ecosystem and finding it hard to find any up to date information on the best way to do things. I'm following along with some NFT minting tutorials to get me up to speed but they are relying on much older `v1.x` instances of this crate.
> 
> ```
>     /// CHECK - address
>     #[account(
>         mut,
>         address=find_metadata_account(&mint.key()).0,
>     )]
>     pub metadata_account: AccountInfo<'info>, // new
>     /// CHECK: address
>     #[account(
>         mut,
>         address=find_master_edition_account(&mint.key()).0,
>     )]
>     pub master_edition_account: AccountInfo<'info>, 
> ```

It would be `Metadata::find_pda(&mint.key()).0` and `MasterEdition::find_pda(&mint.key()).0`

**Comment by danenbm** [comment]
Sorry for the delayed response.  You have probably already worked around this by now, but wanted to let you know that at this point we are pretty far down the path of not releasing program crates.  I think the best bet for your use case is forking it.  And since cargo supports GitHub deps it should be fairly straightforward.  Can that work for your scenario?

**Comment by andreisilviudragnea** [comment]
We just duplicated some missing constants from the program code for now, it should be ok for us for now.
