### ISSUE TITLE
can't install, see error below

### ISSUE THREAD

**Issue by d3g4-deployer** [metaplex-foundation/mpl-token-metadata#82]
npm: '10.2.4',
node: '20.11.0',

command: npm install @metaplex-foundation/mpl-token-metadata

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @metaplex-foundation/umi@0.9.0
npm ERR! node_modules/@metaplex-foundation/umi
npm ERR!   @metaplex-foundation/umi@"^0.9.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @metaplex-foundation/umi@"^0.8.2" from @metaplex-foundation/mpl-token-metadata@3.1.2
npm ERR! node_modules/@metaplex-foundation/mpl-token-metadata
npm ERR!   @metaplex-foundation/mpl-token-metadata@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by alexzh3** [comment]
Have the same error.

**Comment by lorisleiva** [comment]
@danenbm @blockiosaurus Could you just change that line 

https://github.com/metaplex-foundation/mpl-token-metadata/blob/2d967e76a71b14a153ea5bc3613eb55b136fac90/clients/js/package.json#L28

to this:

```
"@metaplex-foundation/umi": ">= 0.8.2 <1"
```

And then trigger a new `patch` update on CI?

That way, it should be compatible with all versions of Umi below v1.

You'll need to do the same with all `mpl-*` clients like `mpl-toolbox`, `mpl-candy-machine`, etc.

**Comment by danenbm** [comment]
Published fix in https://www.npmjs.com/package/@metaplex-foundation/mpl-token-metadata/v/3.1.3
